# DeerFlow 并行化优化配置文件
# 此文件定义了并行处理优化的各种参数和设置

# 全局优化设置
global:
  # 默认优化级别: basic, standard, advanced, maximum
  default_optimization_level: "standard"
  
  # 是否启用智能任务分解
  enable_intelligent_task_decomposition: true
  
  # 是否启用动态资源分配
  enable_dynamic_resource_allocation: true
  
  # 是否启用自适应负载均衡
  enable_adaptive_load_balancing: true
  
  # 是否启用性能监控
  enable_performance_monitoring: true

# 并行执行器配置
parallel_executor:
  # 基础配置
  basic:
    max_workers: 4
    timeout_seconds: 300.0
    enable_caching: true
    enable_rate_limiting: false
    enable_error_recovery: true
    batch_size: 5
    
  # 标准配置
  standard:
    max_workers: 8
    timeout_seconds: 600.0
    enable_caching: true
    enable_rate_limiting: true
    enable_error_recovery: true
    batch_size: 10
    
  # 高级配置
  advanced:
    max_workers: 12
    timeout_seconds: 900.0
    enable_caching: true
    enable_rate_limiting: true
    enable_error_recovery: true
    batch_size: 15
    enable_intelligent_scheduling: true
    enable_resource_prediction: true
    
  # 最大配置
  maximum:
    max_workers: 16
    timeout_seconds: 1200.0
    enable_caching: true
    enable_rate_limiting: true
    enable_error_recovery: true
    batch_size: 20
    enable_intelligent_scheduling: true
    enable_resource_prediction: true
    enable_ml_optimization: true

# 智能任务分解器配置
task_decomposer:
  # 任务复杂度阈值
  complexity_thresholds:
    simple: 0.3
    moderate: 0.6
    complex: 0.8
    very_complex: 1.0
  
  # 最大分解深度
  max_decomposition_depth: 3
  
  # 最小任务大小
  min_task_size: 1
  
  # 最大子任务数量
  max_subtasks: 10
  
  # 依赖分析配置
  dependency_analysis:
    enable_circular_detection: true
    max_dependency_depth: 5
    dependency_timeout: 30.0

# 动态资源分配器配置
resource_allocator:
  # CPU 使用率阈值
  cpu_thresholds:
    low: 30.0
    medium: 60.0
    high: 85.0
    critical: 95.0
  
  # 内存使用率阈值
  memory_thresholds:
    low: 40.0
    medium: 70.0
    high: 85.0
    critical: 95.0
  
  # 资源调整策略
  adjustment_strategy:
    # 调整间隔（秒）
    adjustment_interval: 10.0
    
    # 最小调整幅度
    min_adjustment: 0.1
    
    # 最大调整幅度
    max_adjustment: 0.5
    
    # 调整平滑因子
    smoothing_factor: 0.3
  
  # 资源预测配置
  prediction:
    # 历史数据窗口大小
    history_window: 100
    
    # 预测算法: linear, exponential, ml
    algorithm: "exponential"
    
    # 预测准确度阈值
    accuracy_threshold: 0.8

# 自适应负载均衡器配置
load_balancer:
  # 负载均衡策略: round_robin, least_loaded, weighted, adaptive
  strategy: "adaptive"
  
  # 负载监控间隔（秒）
  monitoring_interval: 5.0
  
  # 负载重新分配阈值
  rebalance_threshold: 0.2
  
  # 工作线程配置
  worker_config:
    # 最小工作线程数
    min_workers: 2
    
    # 最大工作线程数
    max_workers: 32
    
    # 线程空闲超时（秒）
    idle_timeout: 300.0
    
    # 线程启动延迟（秒）
    startup_delay: 1.0
  
  # 任务迁移配置
  task_migration:
    # 是否启用任务迁移
    enable_migration: true
    
    # 迁移触发阈值
    migration_threshold: 0.3
    
    # 最大迁移次数
    max_migrations: 3

# 系统资源监控配置
resource_monitor:
  # 监控间隔（秒）
  monitoring_interval: 2.0
  
  # 历史数据保留时间（秒）
  history_retention: 3600.0
  
  # 监控指标
  metrics:
    - "cpu_usage"
    - "memory_usage"
    - "disk_io"
    - "network_io"
    - "task_queue_size"
    - "active_workers"
  
  # 告警配置
  alerts:
    # CPU 使用率告警阈值
    cpu_alert_threshold: 90.0
    
    # 内存使用率告警阈值
    memory_alert_threshold: 90.0
    
    # 任务队列长度告警阈值
    queue_alert_threshold: 100
    
    # 告警冷却时间（秒）
    alert_cooldown: 300.0

# 缓存配置
caching:
  # 分层缓存配置
  hierarchical:
    # L1 缓存（内存）
    l1_cache:
      max_size: 1000
      ttl_seconds: 300
      
    # L2 缓存（本地存储）
    l2_cache:
      max_size: 10000
      ttl_seconds: 3600
      
    # L3 缓存（分布式）
    l3_cache:
      max_size: 100000
      ttl_seconds: 86400
  
  # 缓存策略
  strategy:
    # 缓存算法: lru, lfu, fifo
    algorithm: "lru"
    
    # 预加载策略
    preload:
      enable: true
      prediction_threshold: 0.7
      max_preload_items: 50
    
    # 缓存失效策略
    invalidation:
      # 失效检查间隔（秒）
      check_interval: 60.0
      
      # 主动失效阈值
      active_threshold: 0.8

# 错误恢复配置
error_recovery:
  # 重试策略
  retry_strategy:
    # 最大重试次数
    max_retries: 3
    
    # 基础延迟（秒）
    base_delay: 1.0
    
    # 指数退避因子
    backoff_factor: 2.0
    
    # 最大延迟（秒）
    max_delay: 60.0
    
    # 抖动因子
    jitter_factor: 0.1
  
  # 熔断器配置
  circuit_breaker:
    # 失败阈值
    failure_threshold: 5
    
    # 恢复超时（秒）
    recovery_timeout: 60.0
    
    # 半开状态测试请求数
    half_open_max_calls: 3
  
  # 降级策略
  fallback:
    # 是否启用降级
    enable_fallback: true
    
    # 降级超时（秒）
    fallback_timeout: 30.0
    
    # 降级质量阈值
    quality_threshold: 0.6

# 性能监控配置
performance_monitoring:
  # 指标收集间隔（秒）
  collection_interval: 5.0
  
  # 指标保留时间（秒）
  retention_period: 86400.0
  
  # 性能指标
  metrics:
    execution_time: true
    throughput: true
    error_rate: true
    resource_utilization: true
    cache_hit_rate: true
    task_completion_rate: true
  
  # 性能报告
  reporting:
    # 报告生成间隔（秒）
    report_interval: 3600.0
    
    # 报告格式: json, csv, html
    format: "json"
    
    # 报告存储路径
    output_path: "./performance_reports/"
  
  # 性能优化建议
  optimization_suggestions:
    # 是否启用优化建议
    enable_suggestions: true
    
    # 建议生成阈值
    suggestion_threshold: 0.7
    
    # 建议更新间隔（秒）
    update_interval: 1800.0

# 日志配置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # 日志格式
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 日志文件配置
  file:
    # 日志文件路径
    path: "./logs/parallel_optimization.log"
    
    # 最大文件大小（MB）
    max_size: 100
    
    # 备份文件数量
    backup_count: 5
    
    # 是否启用日志轮转
    rotation: true
  
  # 控制台日志
  console:
    # 是否启用控制台输出
    enable: true
    
    # 控制台日志级别
    level: "INFO"

# 安全配置
security:
  # 资源限制
  resource_limits:
    # 最大内存使用（MB）
    max_memory: 8192
    
    # 最大CPU使用率（%）
    max_cpu: 90.0
    
    # 最大并发任务数
    max_concurrent_tasks: 100
    
    # 最大执行时间（秒）
    max_execution_time: 3600.0
  
  # 访问控制
  access_control:
    # 是否启用访问控制
    enable: false
    
    # 允许的IP地址列表
    allowed_ips: []
    
    # API密钥验证
    api_key_required: false
  
  # 数据保护
  data_protection:
    # 是否加密敏感数据
    encrypt_sensitive_data: true
    
    # 数据保留策略
    retention_policy: "30_days"
    
    # 是否启用审计日志
    audit_logging: true

# 实验性功能
experimental:
  # 机器学习优化
  ml_optimization:
    # 是否启用ML优化
    enable: false
    
    # ML模型路径
    model_path: "./models/optimization_model.pkl"
    
    # 训练数据收集
    collect_training_data: true
    
    # 模型更新间隔（秒）
    model_update_interval: 86400.0
  
  # 分布式处理
  distributed_processing:
    # 是否启用分布式处理
    enable: false
    
    # 集群节点配置
    cluster_nodes: []
    
    # 负载分发策略
    distribution_strategy: "hash_based"
  
  # GPU加速
  gpu_acceleration:
    # 是否启用GPU加速
    enable: false
    
    # GPU设备ID
    device_id: 0
    
    # GPU内存限制（MB）
    memory_limit: 4096